services:
  broker:
    build:
      context: .
      dockerfile: ./jtasklet.Dockerfile
    hostname: broker-1
    user: "1000:1000"
    command: > 
        broker 
        -v debug 
        --super-peers ebe2b999bbe7c7e2a0ac58dd1f4c806eeb8a828a0807467579a4efe4be3f516f=195.37.209.24:22527 
        --scheduler s1
    restart: always
    volumes:
      - ./experiment/broker:/jtasklet
