version: '3.4'

services:
  broker:
    build: .
    hostname: broker-1
    command: > 
        broker 
        -v debug 
        --super-peers c0900bcfabc493d062ecd293265f571edb70b85313ba4cdda96c9f77163ba62d=sp-fkb1.drasyl.org:22527 
        --scheduler s1
    restart: always
    volumes:
      - ./experiment/broker:/jtasklet
  vm:
    build: .
    hostname: vm-${INDEX}
    command: > 
        vm 
        -v debug
        --tags edge 
        --benchmark-runs 1 
        --broker af0dec7914141c90a805842cb87642d59ed389f4a7fc95f6daf30186dc97226b 
        --super-peers c0900bcfabc493d062ecd293265f571edb70b85313ba4cdda96c9f77163ba62d=sp-fkb1.drasyl.org:22527
    restart: always
    volumes:
      - ./experiment/vms/vm-${INDEX}:/jtasklet
  consumer:
    build: .
    hostname: consumer-1
    command: > 
        offload 
        -v debug
        --relay-only 
        --tags uhh,edge,cloud 
        --priority 1 
        --task tasks/primes.js 
        --broker af0dec7914141c90a805842cb87642d59ed389f4a7fc95f6daf30186dc97226b 
        --super-peers c0900bcfabc493d062ecd293265f571edb70b85313ba4cdda96c9f77163ba62d=sp-fkb1.drasyl.org:22527 
        1 2500
    restart: always
    volumes:
      - ./experiment/consumer:/jtasklet
