version: '3.4'

services:
  broker:
    image: git.informatik.uni-hamburg.de:4567/sane-public/drasyl/jtasklet
    command: broker --verbose info --bind 0.0.0.0:22527
    volumes:
      - ${PWD}/broker:/jtasklet

  provider:
    image: git.informatik.uni-hamburg.de:4567/sane-public/drasyl/jtasklet
    command: vm --verbose info --bind 0.0.0.0:22527 --broker ${BROKER}
    volumes:
      - ${PWD}/provider:/jtasklet
