version: '3.4'

services:
  vm-1:
    build:
      context: .
      dockerfile: ./jtasklet.Dockerfile
    hostname: vm-1
    user: "1000:1000"
    command: >
      vm 
      -v debug
      --tags edge 
      --benchmark-runs 1 
      --broker af0dec7914141c90a805842cb87642d59ed389f4a7fc95f6daf30186dc97226b 
      --super-peers ebe2b999bbe7c7e2a0ac58dd1f4c806eeb8a828a0807467579a4efe4be3f516f=195.37.209.24:22527
    restart: always
    volumes:
      - ./experiment/vms/vm-1:/jtasklet
  vm-2:
    build:
      context: .
      dockerfile: ./jtasklet.Dockerfile
    hostname: vm-2
    user: "1000:1000"
    command: >
      vm 
      -v debug
      --tags edge 
      --benchmark-runs 1 
      --broker af0dec7914141c90a805842cb87642d59ed389f4a7fc95f6daf30186dc97226b 
      --super-peers ebe2b999bbe7c7e2a0ac58dd1f4c806eeb8a828a0807467579a4efe4be3f516f=195.37.209.24:22527
    restart: always
    volumes:
      - ./experiment/vms/vm-2:/jtasklet
