name: drasyl-cli Native Image Windows

on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 6 * * 1' # every monday 6am

jobs:
  build:
    name: Builds Native Image of drasyl-cli for Windows
    runs-on: windows-2016

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4
      - name: Download GraalVM
        run: Invoke-RestMethod -Uri https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-windows-amd64-21.0.0.2.zip -OutFile 'graal.zip'
      - name: Install GraalVM
        run: Expand-Archive -path 'graal.zip' -destinationpath '.'
      - name: Install Native Image
        run: graalvm-ce-java11-21.0.0.2\bin\gu.cmd install native-image
      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: choco install visualstudio2017-workload-vctools
      - name: Build Native Image
        shell: cmd
        env:
          JAVA_HOME: ./graalvm-ce-java11-21.0.0.2
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          ./mvnw -Pnative -DskipTests package
      - name: Package Build
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          New-Item "./drasyl-cli-windows-amd64-snapshot/bin" -ItemType Directory -ea 0
          Move-Item -Path ./drasyl.exe -Destination "./drasyl-cli-windows-amd64-snapshot/bin"
          Copy-Item "./LICENSE" -Destination "./drasyl-cli-windows-amd64-snapshot"
          Compress-Archive -Path "./drasyl-cli-windows-amd64-snapshot" -Update -DestinationPath ./drasyl-cli-windows-amd64-snapshot.zip
      - name: Publish artifact
        if: success()
        uses: actions/upload-artifact@v2.2.2
        with:
          name: drasyl-cli-windows-amd64-snapshot
          path: ./drasyl-cli-windows-amd64-snapshot.zip
