name: drasyl-cli Native Image Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Builds Native Image of drasyl-cli for Windows
    runs-on: macOS-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4
      - name: Download GraalVM
        run: Invoke-RestMethod -Uri https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0.2/graalvm-ce-java11-windows-amd64-21.0.0.2.zip -OutFile 'graal.zip'
      - name: Install GraalVM
        run: Expand-Archive -path 'graal.zip' -destinationpath '.'
      - name: Install Native Image
        run: graalvm-ce-java11-21.0.0.2\bin\gu.cmd install native-image
      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: choco install visualstudio2017-workload-vctools
      - name: Build Native Image
        env:
          JAVA_HOME: ./graalvm-ce-java11-21.0.0.2
          MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
          MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
        run: ./mvnw $MAVEN_CLI_OPTS -Pnative -DskipTests package
      - name: Package Build
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          mkdir -p drasyl-cli-macos-amd64-snapshot/bin
          mv ./drasyl drasyl-cli-macos-amd64-snapshot/bin
          cp ./LICENSE drasyl-cli-macos-amd64-snapshot/
          zip -r drasyl-cli-macos-amd64-snapshot.zip ./drasyl-cli-macos-amd64-snapshot -x '*.DS_Store*' -x '__MAC_OSX'
          New-Item "./drasyl-cli-windows-amd64-snapshot/bin" -ItemType Directory -ea 0
          Move-Item -Path ./drasyl.exe -Destination "./drasyl-cli-windows-amd64-snapshot/bin"
          Copy-Item "./LICENSE" -Destination "./drasyl-cli-windows-amd64-snapshot"
          Compress-Archive -Path "./drasyl-cli-windows-amd64-snapshot" -Update -DestinationPath ./drasyl-cli-windows-amd64-snapshot.zip
      - name: Upload Snapshot
        if: success() && github.event_name == 'push'
        uses: actions/upload-artifact@v2.2.2
        with:
          name: drasyl-cli-windows-amd64-snapshot
          path: drasyl-cli-windows-amd64-snapshot.zip
