name: Build and Deploy Java API

on:
  push:
    branches:
      - master
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        env:
          MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
        run: ./mvnw --batch-mode --errors --fail-at-end --show-version --update-snapshots -DinstallAtEnd=true -DdeployAtEnd=true --activate-profiles api -Dcheckstyle.skip -Drevapi.skip -DskipTests -Djacoco.skip package javadoc:aggregate
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Java API
          path: target/reports/apidocs/*
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout https://github.com/drasyl/api.drasyl.org
        uses: actions/checkout@v4.1.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: drasyl/api.drasyl.org
      - name: Get branch name
        id: vars
        run: echo short_ref=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT
      - name: Delete old Java API
        run: rm -rf ${{ steps.vars.outputs.short_ref }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Java API
          path: ${{ steps.vars.outputs.short_ref }}
      - uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: Update Java API for branch ${{ steps.vars.outputs.short_ref }}
          commit_user_name: drasyl-bot
          commit_user_email: ${{ secrets.DRASYL_BOT_EMAIL }}
          commit_author: drasyl-bot <${{ secrets.DRASYL_BOT_EMAIL }}>
