name: Build and Deploy Docs
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          echo "Download documentation generator"
          curl -sfL https://raw.githubusercontent.com/containous/structor/master/godownloader.sh | sudo bash -s -- -b $GOPATH/bin ${STRUCTOR_VERSION}
        env:
          STRUCTOR_VERSION: v1.11.2
      - name: Build
        run: |
          echo "Build documentation"
          cd docs/
          sudo "$GOPATH/bin/structor" --owner="drasyl-overlay" --repo-name="drasyl" \
            --rqts-url="https://raw.githubusercontent.com/drasyl-overlay/drasyl/master/docs/requirements.txt" \
            --dockerfile-url="https://raw.githubusercontent.com/drasyl-overlay/drasyl/master/docs/docs.Dockerfile" \
            --menu.js-url="https://raw.githubusercontent.com/drasyl-overlay/drasyl/master/docs/theme/structor-menu.js.gotmpl" \
            --exp-branch=master --force-edit-url --debug
      - name: Upload Docs Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs-artifact
          path: docs/site
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Download Docs Artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs-artifact
          path: docs/site
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          publish_branch: gh-pages
