name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '15' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots verify
      - name: Publish artifact
        if: success()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: drasyl-cli
          path: drasyl-*.zip
