code-navigation:
  stage: visualize
  image: haynes/lsifjava:latest
  allow_failure: true # recommended
  script:
    - /opt/lsifjava/bin/lsifjava -projectRoot ./ -out dump.lsif
  artifacts:
    reports:
      lsif: dump.lsif
  except:
    - master
    - /^v\d+\.\d+/
