code-navigation:
  stage: visualize
  image: sourcegraph/lsif-java:latest
  allow_failure: true # recommended
  script:
    - lsif-java index --build-tool Maven --output dump.lsif
  artifacts:
    reports:
      lsif: dump.lsif
  except:
    - master
    - /^v\d+\.\d+/
