# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
docker-build:
  stage: build
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:v1.15.0"
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: 1
    AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--platform linux/amd64,linux/arm/v7,linux/arm64/v8"
  services:
    - docker:20.10.16-dind
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - docker buildx create --use
    - /build/build.sh
  # sometimes cloudflare.docker.com misbehaving
  retry: 2
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
