image: drasyl/drasyl-build-images:jdk-11-maven-3.6.3-gpg-pinentry-tty

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  GIT_DEPTH: 0 # disable git shallow clone for SonarQube https://docs.sonarqube.org/8.5/analysis/gitlab-cicd/?q=cache:iXz6-up8hpIJ:https://docs.sonarqube.org/8.5/analysis/gitlab-cicd/+&cd=1&hl=de&ct=clnk&gl=de

cache:
  paths:
    - .m2/repository

.maven-base: &maven-base
  before_script:
    - export GPG_TTY=$(tty)
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
  after_script:
    - for file in drasyl-*.zip; do sha256sum "$file" | awk '{print $1}' > "$file.sha256"; done
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' drasyl-all/target/site/jacoco-aggregate/jacoco.csv
  coverage: '/\d+.\d+ \% covered/'
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    paths:
      - "drasyl-*.zip"
      - "drasyl-*.zip.sha256"
      - "drasyl-all/target/site/jacoco-aggregate/jacoco.xml"
  needs: [ ]

maven-verify:
  <<: *maven-base
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify -Prelease,ossrh sonar:sonar'
  except:
    - master
    - /^v\d+\.\d+/

maven-deploy:
  <<: *maven-base
  stage: deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -Prelease,ossrh clean verify source:jar gpg:sign install:install deploy:deploy sonar:sonar'
  only:
    - master
    - /^v\d+\.\d+/
