#
# Example config to operate a node as a super peer
#

drasyl {
  network.id = 3
  intra-vm-discovery.enabled = false
  remote {
    bind-port = 22527
    expose.enabled = false
    super-peer.enabled = false
    local-host-discovery.enabled = false
    local-network-discovery.enabled = false
    message.arm.protocol.enabled = false
    message.arm.application.enabled = false
  }
}
